### ISSUE TITLE
Broken C++ colors in VS 2022

### ISSUE THREAD

**Issue by Knose1** [LITDARK/Dark-Transparency-Theme#1]
With the latest version of the theme, the code is unreadable in C++ :
![image](https://user-images.githubusercontent.com/34002600/144517271-83e2e30f-3640-453a-8849-d1361214a5ac.png)

How I fixed it on my version (I'm gonna give some tips too so that users having the same problem can also fix it on their version):  
I went back on the built-in dark theme and listed every colour (RGB) from `C/C++ User Keywords` to `C++ Variables` 
(See `Options>Environment>Fonts and Colors`)

Then I applied the colours on `Dark Transparency` in `Options>Environment>Fonts and Colors`  

[C++_FontColor_Default_DarkTheme_VS2022.txt](https://github.com/LITDARK/Dark-Transparency-Theme/files/7645623/C%2B%2B_FontColor_Default_DarkTheme_VS2022.txt)
This text file contains every colour I listed from `C/C++ User Keywords` to `C++ Variables`  

Here's the result: 
![image](https://user-images.githubusercontent.com/34002600/144519562-05e0c69b-babe-4fd7-bc4c-4e9fbd5e169a.png)

**Comment by LITDARK** [comment]
Thanks for testing this theme. I will update it later :)

**Comment by LITDARK** [comment]
Fixed in [v1.0.2](https://github.com/LITDARK/Dark-Transparency-Theme/releases/tag/v1.0.2)
